apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-webpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-webpage
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: kubernetes-webpage
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: kubernetes-base
        image: kubernetesacrapp.azurecr.io/kubernetes_webpage:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-webpage
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: kubernetes-webpage
